#include "ServerMessageFactory.h"
#include <QDebug>


//QByteArray jsonString = ClientMessageFactory::createInsertMessage(symbol);
//m_socket.sendTextMessage(jsonString);

QByteArray ServerMessageFactory::createNewClientMessage(const Account *account) {
    QJsonObject l_obj;
    l_obj.insert("action", "newClient");    
    QJsonValue jsonAccount(account->toJson());
    l_obj.insert("account", jsonAccount);

    QJsonDocument l_doc(l_obj);
    return l_doc.toJson(QJsonDocument::Indented);
}


// if "response" == false then "account" must be null
QByteArray ServerMessageFactory::createLoginReply(bool response, const Account *account, QList<QString>& nameDocuments) {
    QJsonObject objToReturn;
    QJsonArray nameDocumentsArray;
    QString responseString;
    if(response)
        responseString = "ok";
    else
        responseString = "fail";

    objToReturn.insert("action","loginRepl");
    objToReturn.insert("response",responseString);
    if(account != nullptr)
        objToReturn.insert("account", account->toJson());

    for(QString nameDocument : nameDocuments){
        nameDocumentsArray.push_back(nameDocument);
    }
    objToReturn.insert("nameDocuments",nameDocumentsArray);

    QJsonDocument docOfObj(objToReturn);
    return docOfObj.toJson(QJsonDocument::Indented);
}


QByteArray ServerMessageFactory::createRegistrationUserReply(bool response, double siteIdOfRegisteredUser){
    QJsonObject objToReturn;
    QString responseString;
    if(response)
        responseString = "ok";
    else
        responseString = "fail";

    //we insert the siteId(generated by the db) in the message
    //so that it's possible to create the related Account object
    objToReturn.insert("action","registerUserRepl");
    objToReturn.insert("response",responseString);
    objToReturn.insert("siteId",siteIdOfRegisteredUser);

    QJsonDocument docOfObj(objToReturn);
    return docOfObj.toJson(QJsonDocument::Indented);
}


QByteArray ServerMessageFactory::createOpenFileReply(bool response, CRDT *crdt, QList<Account*>& accounts){
    QJsonObject objToReturn;
    QJsonArray crdtFormattedJson;
    QJsonArray accountsFormattedJson;
    QString responseString;
    responseString = response ? "ok" : "fail";

    objToReturn.insert("action", "openFileRepl");
    objToReturn.insert("response", responseString);

    if (response) {
        crdtFormattedJson = crdt->toJson();
        objToReturn.insert("crdt", crdtFormattedJson);

        for (Account* ac : accounts) {
            QJsonValue jsonAccount = QJsonValue(ac->toJson());
            accountsFormattedJson.append(jsonAccount);
        }
        objToReturn.insert("accounts", accountsFormattedJson);
    }

    QJsonDocument docOfObj(objToReturn);
    return docOfObj.toJson(QJsonDocument::Indented);
}

